version: '3'
services:
  redis:
    image: redis
  proxy:
    build:
      context: .
      dockerfile: contained.Dockerfile
    command: ["./wait-for-redis.sh", "redis-proxy-http", "-redis-host=redis"]
    depends_on:
      - redis
    ports:
      - "4000:4000"